version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: storagebox-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./data/pg-data:/var/lib/postgresql/data  

  redis:
    image: redis:latest
    container_name: storagebox-redis
    ports:
      - "6379:6379"

  server:
    container_name: storagebox-server
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - ./data/uploads:/app/uploads  

  website:
    container_name: storagebox-website
    build:
      context: ./website  
      dockerfile: Dockerfile  
    ports:
      - "4001:4001"  

  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    ports:
      - "9100:9100"
    command:
      - '--path.rootfs=/host'
    pid: host
    restart: unless-stopped
    volumes:
      - './data/node_exporter-data:/host:ro,rslave'

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./data/prometheus-data:/etc/prometheus

  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    environment:
      GF_SECURITY_ALLOW_EMBEDDING: true
      GF_FEATURE_TOGGLES_ENABLE: publicDashboards
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    restart: unless-stopped

volumes:
  grafana-data:
