version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: tus
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  app:
    container_name: server
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      JWT_SECRET: your-secret-key
      DATABASE_URL: postgresql://postgres:123@postgres:5432/tus
      REDIS_URL: redis://redis:6379/0
    ports:
      - "4000:4000"
    depends_on:
      - postgres
