---
- name: Setup Local Environment
  hosts: localhost
  become: true

  # roles:
  #     - install_prerequisites
  tasks:

    - name: Include Variables
      include_vars:
        file: vars.yml

    # - name: Run Docker Compose Up
    #   ansible.builtin.shell: |
    #     docker-compose up -d
    #   args:
    #     chdir: "{{ playbook_dir }}/.."


    - name: Update Nginx configuration
      ansible.builtin.copy:
        content: |
          http {
              server {
                  listen 80;
                  server_name {{domain.website}};

                  location / {
                      proxy_pass http://localhost/4001;
                      proxy_set_header Host $http_host;
                      proxy_set_header X-Real-IP $remote_addr;
                      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                      proxy_set_header X-Forwarded-Proto $scheme;
                      proxy_set_header X-Forwarded-Host $http_host;
                  }
              }

              server {
                  listen 80;
                  server_name {{domain.server}};

                  location / {
                      proxy_pass http://localhost/4000;
                      proxy_set_header Host $http_host;
                      proxy_set_header X-Real-IP $remote_addr;
                      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                      proxy_set_header X-Forwarded-Proto $scheme;
                      proxy_set_header X-Forwarded-Host $http_host;
                  }
              }

              server {
                  listen 80;
                  server_name {{domain.grafana}};

                  location / {
                      proxy_pass http://localhost/3000;
                      proxy_set_header Host $http_host;
                      proxy_set_header X-Real-IP $remote_addr;
                      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                      proxy_set_header X-Forwarded-Proto $scheme;
                      proxy_set_header X-Forwarded-Host $http_host;
                  }
              }
          }
          events {}
        dest: /etc/nginx/nginx.conf

    - name: Reload Nginx
      ansible.builtin.command: nginx -s reload
